### ISSUE TITLE
First example in docs gives 404

### ISSUE THREAD

**Issue by Robsteranium** [hypermedia-app/Alcaeus#234]
The [basic usage example on the docs](https://alcaeus.hydra.how/latest/#/README?id=basic-usage) is:

    await Hydra.loadResource('https://sources.test.wikibus.org/');

This URL returns:

    {"type":"http://tempuri.org/NotFoundError","title":"Resource not found","status":404}

**Comment by tpluscode** [comment]
Hi. Thank's for pointing that out. I was working on new back end for that and kind of stopped unfinished. Reverted and all the `test.wikibus.org` requests should be functioning again
