### ISSUE TITLE
getProperties() does not expose the value of literals

### ISSUE THREAD

**Issue by johnslaughter-ihsmarkit** [hypermedia-app/Alcaeus#248]
I am calling the helper method `getProperties` on a resource. I would expect that I could get all defined values off of the `objects` object. However, if the value of the property is a literal (e.g. `{name: 'test'}`) no values are returned via the `objects` object.

From preliminary investigation, I believe the source might be from the use of `getArray()` which won't return literals (If I'm not mistaken)

https://github.com/hypermedia-app/Alcaeus/blob/079bed7fa32bab74f2b63deeec482df4748d455f/src/Resources/CoreMixins/HydraResource.ts#L104

I believe this is a regression because this seems to be working on v1.1.1 (via the wikibus.org site).

**Comment by tpluscode** [comment]
Indeed, and interestingly it changed as result of fix in [this commit](https://github.com/tpluscode/rdfine/commit/451201e01e75eb6855cc400e02041bdb6a35e16c)

See that `getArray` is generic, intending to return only resources and it was in fact a "bug" that it did not filter out literals.

Anyway, I agree that it should not be like that in Alcaeus. Will fix soon 👍
