### ISSUE TITLE
Support for JSON-LD @base keyword and relative IRIs

### ISSUE THREAD

**Issue by lambdakris** [hypermedia-app/Alcaeus#289]
I think I have stumbled across an issue of sorts. It is a bit nuanced so I've prepared a repro that I hope will help: [relative-iri-example.zip](https://github.com/hypermedia-app/Alcaeus/files/8336769/relative-iri-example.zip). 

The repro consists of a backend in ASP.NET 6 and a frontend in Angular 12. 

To run the backend 
```
dotnet restore
dotnet run
```

To run the frontend
```
npm install
npm start
```

Once everything is running, launch the browser developer tools and navigate to `http://localhost:4300/event-planner`

If you take a look at the console, you should be able to make out 3 separate sections
1. Working Resource
1. Problem Resource 1 - ...
1. Problem Resource 2 - ...

Under the "Working Resource" section, you should see a printing of Help/ApiDoc, Home/EntryPoint, and Properties. This represents the ideal/desired state.

Under the "Problem Resource 1 - ..." section, you should see a similar printing, except that the value of the eventList property is a relative IRI.

Under the "Problem Resource 2 - ..." section, again, you should see a similar printing, except that the eventList property is entirely missing.
 
The difference in these 3 seems to stem from how the resource is constructed. The resource instance that comes from the backend for each can be viewed by looking at the contents of the files under `backend/Stubs/event-planner`. 
- Working Resource -> home.json
- Problem Resource 1 -> home-problem1.json
- Problem Resource 2 -> home-problem2.json

In the case of Problem Resource 1, my concern is that despite the use of the @base keyword, the value of the eventList property remains a relative IRI where I would have expected it to have become fully qualified.

In the case of Problem Resource 2, my concern is that using a relative IRI for the @id of the root resource/subject seems to break some sort of mapping between the fully qualified IRI that is used to resolve the resource and the relative IRI that is used as the value/object of the @id of the resource.

I admit that I am not entirely certain that Alcaeus should work one way or the other in either of these cases, but it did catch me off guard so I figured I'd open an issue to start a discussion around it.

Please let me know if I can provide any more information or background and thank you!

**Comment by tpluscode** [comment]
Hello @lambdakris. I looked at your documents, for now without actually running but I think I may have found your issue.

Please see `home-problem1.json` with inlined `@context` in the JSON-LD playground: https://tinyurl.com/y8hmvge2

The problem here is that the value of `eventList` is interpreted as a literal value. You would need. to apply one of two changes. Either make it an URI explicitly

```diff
-  "eventList": "/event-list"
+  "eventList": { "@id": "/event-list" }
```

Or redefine `eventList` [in the context](https://www.w3.org/TR/json-ld11/#type-coercion)

```diff
-      "eventList": "planner:eventList",
+      "eventList": { "@id": "planner:eventList", "@type": "@id" },
```

**Comment by lambdakris** [comment]
Thanks @tpluscode , I applied the change you suggested and it is working!
